# Generated by Django 5.0.1 on 2024-02-07 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('carnet_id', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(choices=[('estudiante', 'Estudiante'), ('trabajador', 'Trabajador')], max_length=255)),
                ('carrera', models.CharField(blank=True, choices=[('ing-informatico', 'Ing. Informático'), ('ing-mecanico', 'Ing. Mecánico'), ('ing-industrial', 'Ing. Industrial'), ('ing-quimico', 'Ing. Químico'), ('ing-agronomo', 'Ing. Agrónomo'), ('lic-contabilidad', 'Lic. Contabilidad'), ('lic-economia', 'Lic. Economía'), ('lic-derecho', 'Lic. Derecho'), ('lic-cultura-fisica', 'Lic. Cultura Física'), ('lic-estudios-socioculturales', 'Lic. Estudios Socioculturales')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_profesional', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('carnet_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Control.paciente')),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('motivo_consulta', models.CharField(max_length=255)),
                ('riesgo_laboral', models.CharField(max_length=255)),
                ('ap_personal', models.CharField(max_length=255)),
                ('ap_familiar', models.CharField(max_length=255)),
                ('habitos_toxicos', models.CharField(max_length=255)),
                ('alergico_medic', models.CharField(max_length=255)),
                ('operaciones', models.CharField(max_length=255)),
                ('transfusion_sangre', models.CharField(max_length=255)),
                ('vacunacion', models.CharField(max_length=255)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.profesional')),
            ],
        ),
    ]
