# Generated by Django 5.0.1 on 2024-02-05 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('ID_PACIENTE', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=255)),
                ('APELLIDOS', models.CharField(max_length=255)),
                ('CARNET_CI', models.CharField(max_length=255)),
                ('EDAD', models.CharField(max_length=255)),
                ('DIRECCION', models.CharField(max_length=255)),
                ('OCUPACION', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('ID_PROFESIONAL', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=255)),
                ('APELLIDOS', models.CharField(max_length=255)),
                ('CARNET_CI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('ID_HISTORIA', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('FECHA_CREACION', models.CharField(max_length=255)),
                ('FECHA_MODIFICACION', models.CharField(max_length=255)),
                ('MOTIVO_CONSULTA', models.CharField(max_length=255)),
                ('RIESGO_LABORAL', models.CharField(max_length=255)),
                ('AP_PERSONAL', models.CharField(max_length=255)),
                ('AP_FAMILIAR', models.CharField(max_length=255)),
                ('HABITOS_TOXICOS', models.CharField(max_length=255)),
                ('ALERGICO_MEDIC', models.CharField(max_length=255)),
                ('OPERACIONES', models.CharField(max_length=255)),
                ('TRANSFUCION_SANGRE', models.CharField(max_length=255)),
                ('VACUNACION', models.CharField(max_length=255)),
                ('PACIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.paciente')),
                ('PROFESIONAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control.profesional')),
            ],
        ),
    ]
