# Generated by Django 5.0.1 on 2024-02-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='FECHA_CREACION',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='FECHA_MODIFICACION',
            field=models.DateField(),
        ),
    ]
