# Generated by Django 5.0.1 on 2024-02-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0002_alter_historiaclinica_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='CARRERA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='OCUPACION',
            field=models.CharField(choices=[('Trabajador', 'Trabajador'), ('Estudiante', 'Estudiante')], max_length=255),
        ),
    ]
