# Generated by Django 5.0.1 on 2024-02-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0004_carrera_alter_paciente_carrera_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='CARRERA',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='OCUPACION',
            field=models.CharField(max_length=255),
        ),
    ]
