# Generated by Django 5.0.1 on 2024-02-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0006_carrera_paciente_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='CARRERA',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
    ]
