# Generated by Django 5.0.1 on 2024-02-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0007_remove_paciente_carrera_delete_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='ID_HISTORIA',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ID_PACIENTE',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='ID_PROFESIONAL',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
